### ISSUE TITLE
Possible Hitbox issue? 

### ISSUE THREAD

**Issue by YOYOK9** [DoubleDoorDevelopment/DRGFlares#11]
When a flare is on a block cannot break the block it is on while standing on it. 

Block breaking tests:
Torch thrown across: https://puu.sh/Ia1U1/85a4995e17.mp4
Thrown straight down: https://puu.sh/Ia1Jv/756eaffad2.mp4

Time trials: time torch/ light lasts
Light: 5 min then went out
Torch: 10 min then torch de-spawns

Did notice during the time trial tests the torch was "bouncing" a little while just sitting there. 
https://puu.sh/Ia1Xo/f9cf1d3cf1.mp4

MC: 1.16.5
Forge: 36.2.0

If more is needed let me know

**Comment by Claycorp** [comment]
Note to self: This is because the block has an interaction shape. Override and set this to none to remove the issue with the lights blocking interactions.
